Use another action for aggregated summary

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -77,30 +77,42 @@ jobs:
         name: junit-final-report
         path: junit-final-report.xml
 
-    - name: Print detail final tests report
-      uses: dorny/test-reporter@v1
-      id: test-reporter
+    - name: Print test summary
+      uses: mikepenz/action-junit-report@v5
       if: success() || failure()
       with:
-        name: 'Aggregated SIPssert Test Report'
-        path: junit-final-report.xml
-        reporter: java-junit
-        fail-on-error: false
-        max-annotations: 0
+        check_name: 'SIPssert tests report'
+        report_paths: junit-final-report.xml
+        annotate_only: true
+        fail_on_failure: true
+        flaky_summary: true
+        detailed_summary: true
+        group_suite: true
 
-    - name: Debug final output values
-      run: |
-        echo "Final output values"
-        echo "${{ steps.test-reporter.outputs.conclusion }}"
-        echo "${{ steps.test-reporter.outputs.passed }}"
-        echo "${{ steps.test-reporter.outputs.failed }}"
-        echo "${{ steps.test-reporter.outputs.skipped }}"
+    # - name: Print detail final tests report
+    #   uses: dorny/test-reporter@v1
+    #   id: test-reporter
+    #   if: success() || failure()
+    #   with:
+    #     name: 'Aggregated SIPssert Test Report'
+    #     path: junit-final-report.xml
+    #     reporter: java-junit
+    #     fail-on-error: false
+    #     max-annotations: 0
 
-    - name: Create badge
-      uses: RubbaBoy/BYOB@v1.3.0
-      with:
-        NAME: sipssert_tests_${{ github.ref_name }}
-        LABEL: Tests
-        STATUS: "${{ steps.test-reporter.outputs.passed }} pass, ${{ steps.test-reporter.outputs.failed }} fail, ${{ steps.test-reporter.outputs.skipped }} skip"
-        COLOR: ${{ steps.test-reporter.outputs.conclusion == 'success' && 'green' || 'red' }}
-        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
+    # - name: Debug final output values
+    #   run: |
+    #     echo "Final output values"
+    #     echo "${{ steps.test-reporter.outputs.conclusion }}"
+    #     echo "${{ steps.test-reporter.outputs.passed }}"
+    #     echo "${{ steps.test-reporter.outputs.failed }}"
+    #     echo "${{ steps.test-reporter.outputs.skipped }}"
+
+    # - name: Create badge
+    #   uses: RubbaBoy/BYOB@v1.3.0
+    #   with:
+    #     name: sipssert_tests_${{ github.ref_name }}
+    #     label: Tests
+    #     status: "${{ steps.test-reporter.outputs.passed }} passed, ${{ steps.test-reporter.outputs.failed }} failed, ${{ steps.test-reporter.outputs.skipped }} skipped"
+    #     color: ${{ steps.test-reporter.outputs.conclusion == 'success' && 'green' || 'red' }}
+    #     github_token: ${{ secrets.ACTIONS_TOKEN }}
